# 12. Data Structures: `Arrays`

An `array` is a data structure in Python that stores a collection of elements of the same type in contiguous memory locations, allowing efficient access to individual elements using indexing.

## 12.1. `numpy` module

`numpy` is a module for working with arrays, which are a type of list but much faster to process.

The array object in `numpy` is called `ndarray`. This data type is widely used in the world of data science, where speed and resources are of great importance.

In [1]:
import numpy as np

We can check the version of `numpy` with the following line of code.

In [2]:
print(np.__version__)

1.25.1


## 12.2. Creating Arrays

To create an `ndarray`, we use the `.array()` method.

We can do this from a list:

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Or alternatively, from a tuple:

In [4]:
b = np.array((1, 2, 3, 4, 5, 6, 7))
print(b)
print(type(b))

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


## 12.4. Dimensiones de un array

The dimension of an array is determined by its depth level.

To determine the dimension of an array, we can use the `.ndim` property.

In current versions of `Python`, if we create an $n$-dimensional array, then all arrays of fixed dimension $m < n$ must contain the same number of elements. That is, if we create a 4-dimensional array, all 3-dimensional arrays must have the same number of elements; likewise, all 2-dimensional arrays must have the same number of elements; and the same goes for 1-dimensional arrays. This is because otherwise, the `.shape` attribute, which we will see next, would not make sense.

In [5]:
d0 = np.array(77)
print(d0.ndim)

d1 = np.array([-1, 0, 1])
print(d1.ndim)

d2 = np.array([[-3, -2], [-1, 0]])
print(d2.ndim)

d3 = np.array([[[1, 2, 3, 4], [4, 3, 2, 1]], [[1, 0, 1, 0], [-1, 1, -1, 1]]])
print(d3.ndim)

0
1
2
3


An array can have any finite number of dimensions.

When creating an `ndarray`, we can specify the number of dimensions we want the array to have using the `ndmin` argument.

In [6]:
a = np.array([-2, -1, 0, 1, 2], ndmin=7)
print("The array a has {} dimensions".format(a.ndim))
print(a)

The array a has 7 dimensions
[[[[[[[-2 -1  0  1  2]]]]]]]


## 12.5. Array `Shape`

**Shape.** It is the number of elements in each dimension.

We calculate it using the `.shape` attribute.

In [7]:
# There are 3 elements in the 1-dimensional array
d1 = np.array([-1, 0, 1])
print(d1.shape)

# There are 2 elements in the 2D array and 2 elements in the 1D arrays
d2 = np.array([[-3, -2], [-1, 0]])
print(d2.shape)

# There are 2 elements in the 3D array, 2 elements in each 2D array, and 4 elements in each 1D array
d3 = np.array([[[1, 2, 3, 4], [4, 3, 2, 1]], [[1, 0, 1, 0], [-1, 1, -1, 1]]])
print(d3.shape)


(3,)
(2, 2)
(2, 2, 4)


The tuple resulting from the `.shape` attribute is interpreted as follows:
* Each element of the tuple indicates the number of elements in each dimension.
* The first index corresponds to the largest dimension, which is the value obtained with `ndim`.
* The last index corresponds to the smallest dimension (dimension 1).

This is where we can observe the reason why all arrays of the same dimension $m$ belonging to an $n$-dimensional array must have the same number of elements.

For example, given a 4D array, all 2D arrays belonging to it must have the same number of elements, which will be the value returned by the tuple resulting from applying `.shape` at the corresponding index, which in this case would be index 2 (the third and penultimate element of the tuple).

## 12.6. Reshaping an Array

**Reshape.** Changing the `shape` of an array.

Through the reshaping process, we can add or remove dimensions, or change the number of elements in each dimension.

**Example**

We'll start with a 1D array with 8 elements and reshape it into a 2D array with 2 1D arrays, each with 4 elements.

In [8]:
d1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("d1 =", d1)
print("Dimension:", d1.ndim)
print("Shape:", d1.shape)

d1 = [1 2 3 4 5 6 7 8]
Dimension: 1
Shape: (8,)


Our 1D array `d1` consists of 8 elements.

In [9]:
d2 = d1.reshape(2, 4)
print("d2 =", d2)
print("Dimension:", d2.ndim)
print("Shape:", d2.shape)

d2 = [[1 2 3 4]
 [5 6 7 8]]
Dimension: 2
Shape: (2, 4)


Our new 2D array `d2` consists of 2 arrays of dimension 1, each with 4 elements. So, in total, we still have the original 8 elements but with a different `shape`.

When performing a reshape, the product of the elements of the resulting tuple from applying `.shape` must match the total number of elements in the original array.

In this case, we started with 8 elements in 1 dimension and ended up with $2 \cdot 4 = 8$ elements distributed across 2 dimensions.

**Example**

In [10]:
d1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print("d1 =", d1)
print("Dimension:", d1.ndim)
print("Shape:", d1.shape)

d1 = [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Dimension: 1
Shape: (16,)


In [11]:
d3 = d1.reshape(2, 4, 2)
print("d3 =", d3)
print("Dimension:", d3.ndim)
print("Shape:", d3.shape)

d3 = [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]
Dimension: 3
Shape: (2, 4, 2)


Our 3D array consists of 2 bidimensional arrays, each with 4 1D arrays, each of which contains 2 elements.

In total, there are $2 \cdot 4 \cdot 2 = 16$ elements, just as we had originally.

**Example**

In [12]:
d2 = np.array([[-10, -9, -8, -7], [-6, -5, -4, -3], [-2, -1, 1, 2], [3, 4, 5, 6], [7, 8, 9, 10]])
print("d2 =", d2)
print("Dimension:", d2.ndim)
print("Shape:", d2.shape)

d2 = [[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   1   2]
 [  3   4   5   6]
 [  7   8   9  10]]
Dimension: 2
Shape: (5, 4)


In [13]:
d5 = d2.reshape(2, 1, 2, 1, 5)
print("d5 =", d5)
print("Dimensión:", d5.ndim)
print("Shape:", d5.shape)

d5 = [[[[[-10  -9  -8  -7  -6]]

   [[ -5  -4  -3  -2  -1]]]]



 [[[[  1   2   3   4   5]]

   [[  6   7   8   9  10]]]]]
Dimensión: 5
Shape: (2, 1, 2, 1, 5)


We have transformed our original 2D array into a 5D array consisting of 2 4D arrays, each of which contains a 3D array, which has 2 2D arrays with 1 1D array inside, consisting of 5 elements. In total, $2 \cdot 1 \cdot 2 \cdot 1 \cdot 5 = 20$.

**Observation:** The result of a `.reshape()` is a `view` of the original array.

In [14]:
print("El array transformado a partir del array d2 del Ejemplo 3 es una view,\npues "
      "al aplicar .base se nos devuelve el array 2D original:\n", d5.base)

El array transformado a partir del array d2 del Ejemplo 3 es una view,
pues al aplicar .base se nos devuelve el array 2D original:
 [[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   1   2]
 [  3   4   5   6]
 [  7   8   9  10]]


When reshaping, it's not always necessary to specify the exact number of one of the dimensions as a parameter of the `.reshape()` method.

If we don't know a dimension, we can simply indicate -1 in the appropriate place, and `numpy` will calculate it for us.

Taking the 2D array from Example 3,

In [15]:
d2 = np.array([[-10, -9, -8, -7], [-6, -5, -4, -3], [-2, -1, 1, 2], [3, 4, 5, 6], [7, 8, 9, 10]])

Suppose we don't know the last dimension when transforming it into the 5D array. In that case, we introduce -1 as a parameter.

In [16]:
d5 = d2.reshape(2, 1, 2, 1, -1)
print("d5 =", d5)
print("Dimension:", d5.ndim)
print("Shape:", d5.shape)

d5 = [[[[[-10  -9  -8  -7  -6]]

   [[ -5  -4  -3  -2  -1]]]]



 [[[[  1   2   3   4   5]]

   [[  6   7   8   9  10]]]]]
Dimension: 5
Shape: (2, 1, 2, 1, 5)


We observe that `numpy` has calculated that dimension for us, which matches the result indicated in Example.

**Observations**

We can only pass -1 as a parameter to the `.reshape()` method for one dimension only.

The use of -1 can be very useful when we want to transform any multidimensional array into a one-dimensional array.

For example, starting from the 5D array in Example 3, we can transform it into a one-dimensional array as follows:

In [17]:
d1 = d5.reshape(-1)
print("d1 =", d1)
print("Dimension:", d1.ndim)
print("Shape:", d1.shape)

d1 = [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   1   2   3   4   5   6   7   8
   9  10]
Dimension: 1
Shape: (20,)


## 12.7. Array Elements

### 12.7.1. One-dimensional Case

We can access the elements of an array using the `[]` syntax.

Remember that in `Python`, indices start at 0.

In [18]:
a = np.array([2, 3, 4, 5, 6])
print(a)

print("First element = ", a[0])
print("Second element = ", a[1])
print("Last element = ", a[-1])

[2 3 4 5 6]
First element =  2
Second element =  3
Last element =  6


### 12.7.2. Multidimensional Case

When accessing elements of a multidimensional array, we need to start by indicating the index of the element at the shallowest level and end by indicating the index of the element at the deepest level, all within `[]` separated by commas.

In the case of a two-dimensional array, as shown below,

In [19]:
a = np.array([[-10, -9], [7, 8]])
a.ndim

2

To access the element -9, we first need to indicate index 0, as the one-dimensional array to which it belongs is located at index 0 of the shallowest level. Next, we will indicate index 1, as that is the position occupied by the element of interest within the one-dimensional array, which is the deepest level in this case:

In [20]:
a[0, 1]

-9

For a three-dimensional array, like the one shown below,

In [21]:
a = np.array([[[1, 2, 3], [-3, -2, -1]], [[4, 5, 6], [7, 8, 9]]])
a.ndim

3

To access the element 7, we first need to indicate index 1, as the two-dimensional array to which it belongs is located at position 1 of the shallowest level. We enter the next level, the two-dimensional array. Now, the position to indicate is 1, as the one-dimensional array occupies that index within the two-dimensional array. Finally, we reach the deepest level, the one-dimensional array, and now we need to indicate index 0, as that is the position occupied by the element of interest within the one-dimensional array.

In [22]:
a[1, 1, 0]

7

Given a multidimensional array, if we want to retrieve an array of lower dimension, we simply need to specify its indices as we would to obtain an element.

Given the previous three-dimensional array `a`, if we want to access the one-dimensional array `[-3, -2, -1]`, then we will indicate the indices 0 and 1 between `[]`. This is because this array is located in the first two-dimensional array, and within this array, it occupies the second position, which is index 1:

In [23]:
a[0, 1]

array([-3, -2, -1])

### 12.7.3. Negative Indices

Similar to lists, elements of `ndarrays` can also be accessed using negative indices.

The index `-1` refers to the last element; `-2` refers to the second-to-last; `-3` refers to the third-to-last; and so on.

In [24]:
a[-1]

array([[4, 5, 6],
       [7, 8, 9]])

## 12.8. Slicing

In `Python`, **slicing** refers to taking elements from a given index up to another provided index.

We already know the syntax:
* `[start:end]` where we go from index `start` to index `end`-1, and do it 1 by 1.
* `[start:end:step]` where we go from index `start` to index `end`-1, and do it by `step` increments.

### 12.8.1. One-dimensional Case

In [25]:
# One-dimensional array
a1 = np.array([9, 8, 7, 6, 5, 4, 3])
print(a1)

# From the second element to the fourth, by 1
print(a1[1:4])

# From the first element to the sixth, by 1
print(a1[:6])

# From the third element to the last, by 1
print(a1[2:])

# From the second element to the sixth, by 2
print(a1[1:6:2])

# From the first element to the fifth, by 2
print(a1[:5:2])

# From the second element to the last, by 3
print(a1[2::3])

# From the first element to the last, by 4
print(a1[::4])

[9 8 7 6 5 4 3]
[8 7 6]
[9 8 7 6 5 4]
[7 6 5 4 3]
[8 6 4]
[9 7 5]
[7 4]
[9 5]


### 12.8.2. Multidimensional Case

In [26]:
# 4-dimensional array
a4 = np.array([[[[-211, -210], [-29, -28], [-27, -26]], [[-25, -24], [-23, -22], [-21, -20]]],
               [[[-111, -110], [-19, -18], [-17, -16]], [[-15, -14], [-13, -12], [-11, -10]]],
               [[[111, 110], [19, 18], [17, 16]], [[15, 14], [13, 12], [11, 10]]],
               [[[211, 210], [29, 28], [27, 26]], [[25, 24], [23, 22], [21, 20]]]])

print(a4.ndim)
print(a4.shape)

4
(4, 2, 3, 2)


The 4-dimensional array `a4` consists of 4 three-dimensional arrays, each of which contains 2 two-dimensional arrays, each of which contains 3 one-dimensional arrays.

In [27]:
# Show from the second to the third 3D array
print(a4[1:3])
print("--------------------")
# From the second 2D array of the first 3D array, show the first two 1D arrays
print(a4[0, 1, :2])
print("--------------------")
# From the second to the last 3D array, show the second 1D array of the first 2D array
print(a4[1:, 0, 1])

[[[[-111 -110]
   [ -19  -18]
   [ -17  -16]]

  [[ -15  -14]
   [ -13  -12]
   [ -11  -10]]]


 [[[ 111  110]
   [  19   18]
   [  17   16]]

  [[  15   14]
   [  13   12]
   [  11   10]]]]
--------------------
[[-25 -24]
 [-23 -22]]
--------------------
[[-19 -18]
 [ 19  18]
 [ 29  28]]


**Observation:** Just like for accessing elements, negative indices also work in array slicing (Negative Slicing).

In [28]:
# From the last two 3D arrays, show the last element of the last 1D array of each 2D array
a4[-2:, :, -1, -1]

array([[16, 10],
       [26, 20]])

## 12.9. Filtering Arrays

Filtering an array involves selecting elements from an existing array that satisfy a condition and creating a new array with those elements.

The syntax is very similar to slicing, but instead, we specify a boolean condition within square brackets. The elements that satisfy the condition will be the ones that remain, while the rest will be omitted.

Another way to see it is that the condition creates a boolean array. Positions occupied by a `True` value will be included in the filtered array, while those occupied by `False` (because they do not satisfy the condition) will be discarded.

In [29]:
a = np.array([4, 3, 2, 3, 4])
b = a[a == 4]
print(b)

[4 4]


In [30]:
a == 4

array([ True, False, False, False,  True])

In [31]:
c = a[a % 2 == 0]
print(c)

[4 2 4]


In [32]:
d = a[a <= 2]
print(d)

[2]


In [33]:
d5[d5 % 2 == 0]

array([-10,  -8,  -6,  -4,  -2,   2,   4,   6,   8,  10])

## 12.10. Data Types in `numpy`

By default, `Python` has the following data types:

* `int`: integer
* `float`: float
* `complex`: complex float
* `bool`: boolean
* `str`: string

In `numpy`, we find additional data types:

* `i`: integer
* `u`: unsigned integer 
* `f`: float
* `c`: complex float
* `b`: boolean
* `m`: timedelta
* `M`: datetime
* `O`: object
* `S`: string
* `U`: unicode string
* `V`: void

To check the data type of an array, we use the `.dtype` method.

In [34]:
a = np.array([1, 2, 3])
print(a)
a.dtype

[1 2 3]


dtype('int32')

In [35]:
a = np.array([1.5, 2.4, 3.7])
print(a)
a.dtype

[1.5 2.4 3.7]


dtype('float64')

In [36]:
a = np.array([1j, 2 + 3j, 3 - 7j])
print(a)
a.dtype

[0.+1.j 2.+3.j 3.-7.j]


dtype('complex128')

In [37]:
a = np.array(["araña", "barco", "colonia"])
print(a)
a.dtype

['araña' 'barco' 'colonia']


dtype('<U7')

In [38]:
a = np.array(["a", "b", "c"])
print(a)
a.dtype

['a' 'b' 'c']


dtype('<U1')

When using the `.array()` method, there is a parameter `dtype` that allows us to define the data type we want the elements of the ndarray to have.

In [39]:
a = np.array([1, 2, 3, 4, 5], dtype = "S")
print(a)
a.dtype

[b'1' b'2' b'3' b'4' b'5']


dtype('S1')

**Observation:** For the data types `i`, `u`, `f`, `S`, and `U`, we can also define the size with the `dtype` parameter.

In [40]:
a = np.array([1, 2, 3, 4, 5], dtype = "i1")
print(a)
a.dtype

[1 2 3 4 5]


dtype('int8')

In [41]:
a = np.array([1, 2, 3, 4, 5], dtype = "i2")
print(a)
a.dtype

[1 2 3 4 5]


dtype('int16')

In [42]:
a = np.array([1, 2, 3, 4, 5], dtype = "f8")
print(a)
a.dtype

[1. 2. 3. 4. 5.]


dtype('float64')

In [43]:
a = np.array([1, 2, 3, 4, 5], dtype = "c16")
print(a)
a.dtype

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


dtype('complex128')

In [44]:
a = np.array([1, 2, 3, 4, 5], dtype = "S2")
print(a)
a.dtype

[b'1' b'2' b'3' b'4' b'5']


dtype('S2')

If we want to change the data type of an existing array, we use the `.astype()` method.

In [45]:
a = np.array([1, 2, 3, 4, 5], dtype="float16")
print("The array a is of type", a.dtype)
b = a.astype("i")
print("The array b is of type", b.dtype)

The array a is of type float16
The array b is of type int32


In [46]:
a = np.array([1, 2, 3, 4, 5], dtype="float16")
print("The array a is of type", a.dtype)
b = a.astype(int)
print("The array b is of type", b.dtype)

The array a is of type float16
The array b is of type int32


In [47]:
a = np.array([1, 0, 3, 0, 5, -10])
print(a)
print("The array a is of type", a.dtype)
b = a.astype(bool)
print(b)
print("The array b is of type", b.dtype)

[  1   0   3   0   5 -10]
The array a is of type int32
[ True False  True False  True  True]
The array b is of type bool


## 12.11. Array Copies and Views

**Copy.** A copy of an array creates a new array exactly like the original.

The copy is not affected by changes applied to the original array.

In [48]:
x = np.array(["a", "b", "c"])
print(x)
x_copy = x.copy()
print(x_copy)

['a' 'b' 'c']
['a' 'b' 'c']


**View.** A view of an array is a reference to the original array.

Changes applied to the original array also affect the view, and vice versa.

In [49]:
y = np.array([1, 2, 3])
print("y =", y)
y_view = y.view()
print("y_view =", y_view)

y = [1 2 3]
y_view = [1 2 3]


If we modify the original, we will see the changes also applied in the view.

In [50]:
y[1] = 0
print("y =", y)
print("y_view =", y_view)

y = [1 0 3]
y_view = [1 0 3]


If we modify the view, we will see the changes also applied in the original array.

In [51]:
y_view[0] = -3
print("y =", y)
print("y_view =", y_view)

y = [-3  0  3]
y_view = [-3  0  3]


To ensure whether we have made a copy or a view, we can use the `.base` method, which will return `None` if it's a copy and will return the original array if it's a view.

In [52]:
z = np.array([1j, 0, -1j])
z_copy = z.copy()
z_view = z.view()

print("z_copy nos devuelve", z_copy.base, "porque es una copia")
print("z_view nos devuelve", z_view.base, "porque es una view")

z_copy nos devuelve None porque es una copia
z_view nos devuelve [ 0.+1.j  0.+0.j -0.-1.j] porque es una view


## 12.12. Loops with arrays

We can iterate over an array just as we did with lists.

### 12.12.1. 1D Array

In [53]:
d1 = np.array(["a", "b", "c"])

for i in d1:
    print(i)

a
b
c


### 12.12.2. 2D Array

In [54]:
d2 = np.array([["a", "b", "c"], [1, 2, 3]])

In [55]:
# Print the elements of the 2D array
for d1 in d2:
    print(d1)

['a' 'b' 'c']
['1' '2' '3']


In [56]:
# Print the elements of the 1D arrays
for d1 in d2:
    for i in d1:
        print(i)

a
b
c
1
2
3


### 12.12.2. 3D Array

In [57]:
d3 = np.array([[["a", "b", "c", "d"], ["e", "f", "g", "h"]], [[1, 2, 3, 4], [5, 6, 7, 8]]])
d3.dtype

dtype('<U11')

In [58]:
# Print the elements of the 3D array
for d2 in d3:
    print(d2)

[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']]
[['1' '2' '3' '4']
 ['5' '6' '7' '8']]


In [59]:
# Print the elements of the 2D arrays
for d2 in d3:
    for d1 in d2:
        print(d1)

['a' 'b' 'c' 'd']
['e' 'f' 'g' 'h']
['1' '2' '3' '4']
['5' '6' '7' '8']


In [60]:
# Imprimimos los elementos de los arrays 1D
for d2 in d3:
  for d1 in d2:
    for i in d1:
      print(i)

a
b
c
d
e
f
g
h
1
2
3
4
5
6
7
8


As we can see, every time we increase the dimension of the array, we need to nest `for` loops to print each of the elements of the 1D arrays.

As an alternative, we could reshape the multidimensional array to a one-dimensional array, but given an array with a sufficiently large dimension, this process would be computationally very costly.

In [61]:
for i in d3.reshape(-1):
    print(i)

a
b
c
d
e
f
g
h
1
2
3
4
5
6
7
8


## 12.13. `numpy` methods and functions

| Function/Method | Description |
|-----------------|-------------|
| `.empty()`      | Return a new array with uninitialized data. |
| `.empty_like()` | Return a new array with the same shape and type as a given array. |
| `.zeros()`      | Return a new array of given shape and type, filled with zeros. |
| `.zeros_like()` | Return a new array of zeros with the same shape and type as a given array. |
| `.ones()`       | Return a new array of given shape and type, filled with ones. |
| `.ones_like()`  | Return a new array of ones with the same shape and type as a given array. |
| `.matrix()`     | Interpret the input as a matrix. |
| `+`             | Add arrays element-wise. |
| `.dot()`        | Dot product of two arrays. |
| `.nditer()`     | Efficient multi-dimensional iterator object. |
| `.ndenumerate()`| Multidimensional index iterator. |
| `.concatenate()`| Concatenate arrays along an existing axis. |
| `.stack()`      | Join a sequence of arrays along a new axis. |
| `.hstack()`     | Stack arrays in sequence horizontally (column wise). |
| `.vstack()`     | Stack arrays in sequence vertically (row wise). |
| `.dstack()`     | Stack arrays in sequence depth wise (along third axis). |
| `.array_split()`| Split an array into multiple sub-arrays. |
| `.split()`      | Split an array into multiple sub-arrays. |
| `.hsplit()`     | Split an array into multiple sub-arrays horizontally (column-wise). |
| `.vsplit()`     | Split an array into multiple sub-arrays vertically (row-wise). |
| `.dsplit()`     | Split array into multiple sub-arrays along the 3rd axis (depth). |
| `.where()`      | Return elements chosen from `x` or `y` depending on condition. |
| `.searchsorted()`| Find indices where elements should be inserted to maintain order. |
| `.sort()`       | Return a sorted copy of an array. |
| `.add()`        | Add arguments element-wise. |
| `.subtract()`   | Subtract arguments, element-wise. |
| `.multiply()`   | Multiply arguments, element-wise. |
| `.divide()`     | Returns a true division of the inputs, element-wise. |
| `.power()`      | First array elements raised to powers from second array, element-wise. |
| `.mod()`        | Return element-wise remainder of division. |
| `.remainder()`  | Return element-wise remainder of division. |
| `.divmod()`     | Return element-wise quotient and remainder simultaneously. |
| `.absolute()`   | Calculate the absolute value element-wise. |
| `.trunc()`      | Return the truncated value of the input, element-wise. |
| `.fix()`        | Round to nearest integer towards zero. |
| `.round()`      | Round elements of the array to the nearest integer. |
| `.floor()`      | Return the floor of the input, element-wise. |
| `.ceil()`       | Return the ceiling of the input, element-wise. |
| `.around()`     | Evenly round to the given number of decimals. |
| `.sum()`        | Sum of array elements over a given axis. |
| `.cumsum()`     | Return the cumulative sum of the elements along a given axis. |
| `.diff()`       | Calculate the n-th discrete difference along the given axis. |
| `.prod()`       | Return the product of array elements over a given axis. |
| `.cumprod()`    | Return the cumulative product of elements along a given axis. |
| `.log()`        | Natural logarithm, element-wise. |
| `.lcm.reduce()` | Returns the least common multiple of the inputs. |
| `.gcd.reduce()` | Returns the greatest common divisor of the inputs. |
| `.unique()`     | Find the unique elements of an array. |
| `.union1d()`    | Find the union of two arrays. |
| `.intersect1d()`| Find the intersection of two arrays. |
| `.setdiff1d()`  | Find the set difference of two arrays. |
| `.setxor1d()`   | Find the set exclusive-or of two arrays. |
| `np.pi`         | The mathematical constant π. |
| `.sin()`        | Trigonometric sine, element-wise. |
| `.cos()`        | Cosine element-wise. |
| `.tan()`        | Compute tangent element-wise. |
| `.deg2rad()`    | Convert angles from degrees to radians. |
| `.rad2deg()`    | Convert angles from radians to degrees. |
| `.arcsin()`     | Inverse sine, element-wise. |
| `.arccos()`     | Trigonometric inverse cosine, element-wise. |
| `.arctan()`     | Trigonometric inverse tangent, element-wise. |
| `.sinh()`       | Hyperbolic sine, element-wise. |
| `.cosh()`       | Hyperbolic cosine, element-wise. |
| `.tanh()`       | Compute hyperbolic tangent element-wise. |
| `.arcsinh()`    | Inverse hyperbolic sine element-wise. |
| `.arccosh()`    | Inverse hyperbolic cosine, element-wise. |
| `.arctanh()`    | Inverse hyperbolic tangent element-wise. |

In [62]:
import numpy as np

# Examples

# Creating an empty array
empty_array = np.empty((2, 3))
print("Empty Array:")
print(empty_array)

# Creating an array with the same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
empty_like_array = np.empty_like(given_array)
print("\nEmpty Array Like Given Array:")
print(empty_like_array)

# Creating an array filled with zeros
zeros_array = np.zeros((2, 3))
print("\nZeros Array:")
print(zeros_array)

# Creating an array of zeros with the same shape and type as a given array
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Array Like Given Array:")
print(zeros_like_array)

# Creating an array filled with ones
ones_array = np.ones((2, 3))
print("\nOnes Array:")
print(ones_array)

# Creating an array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes Array Like Given Array:")
print(ones_like_array)

# Example of adding arrays element-wise
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
sum_array = array1 + array2
print("\nSum of Arrays Element-wise:")
print(sum_array)

# Example of dot product of two arrays
dot_product = np.dot(array1, array2)
print("\nDot Product of Arrays:")
print(dot_product)

# Example of interpreting input as a matrix
matrix_array = np.matrix([[1, 2], [3, 4]])
print("\nMatrix:")
print(matrix_array)

Empty Array:
[[0. 0. 0.]
 [0. 0. 0.]]

Empty Array Like Given Array:
[[          0  1072693248           0]
 [ 1074266112           0 -1071906816]]

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]

Zeros Array Like Given Array:
[[0 0 0]
 [0 0 0]]

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]]

Ones Array Like Given Array:
[[1 1 1]
 [1 1 1]]

Sum of Arrays Element-wise:
[[ 6  8]
 [10 12]]

Dot Product of Arrays:
[[19 22]
 [43 50]]

Matrix:
[[1 2]
 [3 4]]


In [63]:
# Example usage of the mentioned methods/functions

# Creating arrays for demonstration
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Example of nditer
print("Using nditer:")
for x in np.nditer(array1):
    print(x, end=' ')
print()

# Example of ndenumerate
print("\nUsing ndenumerate:")
for index, value in np.ndenumerate(array1):
    print(index, value)

# Example of concatenate
concatenated_array = np.concatenate((array1, array2), axis=0)
print("\nConcatenated Array:")
print(concatenated_array)

# Example of stack
stacked_array = np.stack((array1, array2))
print("\nStacked Array:")
print(stacked_array)

# Example of hstack
hstacked_array = np.hstack((array1, array2))
print("\nHorizontally Stacked Array:")
print(hstacked_array)

# Example of vstack
vstacked_array = np.vstack((array1, array2))
print("\nVertically Stacked Array:")
print(vstacked_array)

# Example of dstack
dstacked_array = np.dstack((array1, array2))
print("\nDepth-wise Stacked Array:")
print(dstacked_array)

# Example of array_split
array_splits = np.array_split(array1, 2)
print("\nArray Split:")
for arr in array_splits:
    print(arr)

# Example of split
splits = np.split(array1, 2)
print("\nSplit:")
for arr in splits:
    print(arr)

# Example of hsplit
hsplits = np.hsplit(array1, 2)
print("\nHorizontal Split:")
for arr in hsplits:
    print(arr)

# Example of vsplit
vsplits = np.vsplit(array1, 2)
print("\nVertical Split:")
for arr in vsplits:
    print(arr)

# Example of dsplit
# Since dsplit requires a 3D array, we'll create one for demonstration
array3d = np.dstack((array1, array2))
dsplits = np.dsplit(array3d, 2)
print("\nDepth-wise Split:")
for arr in dsplits:
    print(arr)

# Example of where
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
condition = np.array([True, False, True, False])
result = np.where(condition, x, y)
print("\nUsing where:")
print(result)

# Example of searchsorted
sorted_array = np.array([1, 3, 5, 7, 9])
indices = np.searchsorted(sorted_array, 6)
print("\nIndices where 6 should be inserted to maintain order:", indices)

# Creating an unsorted array
unsorted_array = np.array([3, 1, 5, 2, 4])

# Sorting the array
sorted_array = np.sort(unsorted_array)

# Printing the sorted array
print("Sorted Array:")
print(sorted_array)

# Note: The original array remains unchanged
print("\nOriginal Array (Unsorted):")
print(unsorted_array)

Using nditer:
1 2 3 4 

Using ndenumerate:
(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4

Concatenated Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Stacked Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Horizontally Stacked Array:
[[1 2 5 6]
 [3 4 7 8]]

Vertically Stacked Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Depth-wise Stacked Array:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

Array Split:
[[1 2]]
[[3 4]]

Split:
[[1 2]]
[[3 4]]

Horizontal Split:
[[1]
 [3]]
[[2]
 [4]]

Vertical Split:
[[1 2]]
[[3 4]]

Depth-wise Split:
[[[1]
  [2]]

 [[3]
  [4]]]
[[[5]
  [6]]

 [[7]
  [8]]]

Using where:
[1 6 3 8]

Indices where 6 should be inserted to maintain order: 3
Sorted Array:
[1 2 3 4 5]

Original Array (Unsorted):
[3 1 5 2 4]


In [64]:
# Example usage of the mentioned methods/functions

# Creating arrays for demonstration
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Example of add()
add_result = np.add(array1, array2)
print("Addition Result:", add_result)

# Example of subtract()
subtract_result = np.subtract(array1, array2)
print("Subtraction Result:", subtract_result)

# Example of multiply()
multiply_result = np.multiply(array1, array2)
print("Multiplication Result:", multiply_result)

# Example of divide()
divide_result = np.divide(array1, array2)
print("Division Result:", divide_result)

# Example of power()
power_result = np.power(array1, array2)
print("Power Result:", power_result)

# Example of mod()
mod_result = np.mod(array1, array2)
print("Modulus Result:", mod_result)

# Example of remainder()
remainder_result = np.remainder(array1, array2)
print("Remainder Result:", remainder_result)

# Example of divmod()
divmod_result = np.divmod(array1, array2)
print("Divmod Result:", divmod_result)

# Example of absolute()
absolute_result = np.absolute(np.array([-1, -2, 3]))
print("Absolute Value Result:", absolute_result)

# Example of trunc()
trunc_result = np.trunc(np.array([1.2, 2.8, 3.5]))
print("Truncated Value Result:", trunc_result)

# Example of fix()
fix_result = np.fix(np.array([-1.2, -2.8, 3.5]))
print("Fixed Value Result:", fix_result)

# Example of round()
round_result = np.round(np.array([1.2, 2.8, 3.5]))
print("Rounded Value Result:", round_result)

# Example of floor()
floor_result = np.floor(np.array([1.2, 2.8, 3.5]))
print("Floor Value Result:", floor_result)

# Example of ceil()
ceil_result = np.ceil(np.array([1.2, 2.8, 3.5]))
print("Ceiling Value Result:", ceil_result)

# Example of around()
around_result = np.around(np.array([1.234, 2.567, 3.789]), decimals=2)
print("Around Value Result:", around_result)

# Example of sum()
sum_result = np.sum(array1)
print("Sum Result:", sum_result)

# Example of cumsum()
cumsum_result = np.cumsum(array1)
print("Cumulative Sum Result:", cumsum_result)

# Example of diff()
diff_result = np.diff(array1)
print("Difference Result:", diff_result)

# Example of prod()
prod_result = np.prod(array1)
print("Product Result:", prod_result)

# Example of cumprod()
cumprod_result = np.cumprod(array1)
print("Cumulative Product Result:", cumprod_result)

# Example of log()
log_result = np.log(array1)
print("Natural Logarithm Result:", log_result)

# Example usage of lcm.reduce() and gcd.reduce()

# Creating arrays for demonstration
array = np.array([6, 8, 10])

# Computing least common multiple (LCM) using lcm.reduce()
lcm_result = np.lcm.reduce(array)
print("Least Common Multiple (LCM):", lcm_result)

# Computing greatest common divisor (GCD) using gcd.reduce()
gcd_result = np.gcd.reduce(array)
print("Greatest Common Divisor (GCD):", gcd_result)

# Example usage of the unique() function

# Creating an array with duplicate elements
array = np.array([1, 2, 2, 3, 3, 4, 5, 5, 6])

# Finding unique elements in the array
unique_elements = np.unique(array)

# Printing the unique elements
print("Unique Elements:", unique_elements)

Addition Result: [5 7 9]
Subtraction Result: [-3 -3 -3]
Multiplication Result: [ 4 10 18]
Division Result: [0.25 0.4  0.5 ]
Power Result: [  1  32 729]
Modulus Result: [1 2 3]
Remainder Result: [1 2 3]
Divmod Result: (array([0, 0, 0]), array([1, 2, 3]))
Absolute Value Result: [1 2 3]
Truncated Value Result: [1. 2. 3.]
Fixed Value Result: [-1. -2.  3.]
Rounded Value Result: [1. 3. 4.]
Floor Value Result: [1. 2. 3.]
Ceiling Value Result: [2. 3. 4.]
Around Value Result: [1.23 2.57 3.79]
Sum Result: 6
Cumulative Sum Result: [1 3 6]
Difference Result: [1 1]
Product Result: 6
Cumulative Product Result: [1 2 6]
Natural Logarithm Result: [0.         0.69314718 1.09861229]
Least Common Multiple (LCM): 120
Greatest Common Divisor (GCD): 2
Unique Elements: [1 2 3 4 5 6]


In [65]:
# Example usage of union1d(), intersect1d(), setdiff1d(), and setxor1d() functions

# Creating arrays for demonstration
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Finding the union of two arrays
union = np.union1d(array1, array2)
print("Union of arrays:", union)

# Finding the intersection of two arrays
intersection = np.intersect1d(array1, array2)
print("Intersection of arrays:", intersection)

# Finding the set difference of two arrays (elements in array1 that are not in array2)
set_diff = np.setdiff1d(array1, array2)
print("Set difference (array1 - array2):", set_diff)

# Finding the set exclusive-or of two arrays (elements that are in only one of the arrays)
set_xor = np.setxor1d(array1, array2)
print("Set exclusive-or of arrays:", set_xor)

Union of arrays: [1 2 3 4 5 6 7]
Intersection of arrays: [3 4 5]
Set difference (array1 - array2): [1 2]
Set exclusive-or of arrays: [1 2 6 7]


In [66]:
# Example usage of trigonometric and hyperbolic functions in NumPy

# Creating an array of angles in degrees
angles_degrees = np.array([0, 30, 45, 60, 90])

# Convert angles from degrees to radians
angles_radians = np.deg2rad(angles_degrees)
print("Angles in Radians:", angles_radians)

# Compute sine of the angles
sine_values = np.sin(angles_radians)
print("Sine Values:", sine_values)

# Compute cosine of the angles
cosine_values = np.cos(angles_radians)
print("Cosine Values:", cosine_values)

# Compute tangent of the angles
tangent_values = np.tan(angles_radians)
print("Tangent Values:", tangent_values)

# Convert angles from radians to degrees
angles_degrees_again = np.rad2deg(angles_radians)
print("Angles in Degrees Again:", angles_degrees_again)

# Compute inverse sine of the sine values
inverse_sine_values = np.arcsin(sine_values)
print("Inverse Sine Values:", inverse_sine_values)

# Compute inverse cosine of the cosine values
inverse_cosine_values = np.arccos(cosine_values)
print("Inverse Cosine Values:", inverse_cosine_values)

# Compute inverse tangent of the tangent values
inverse_tangent_values = np.arctan(tangent_values)
print("Inverse Tangent Values:", inverse_tangent_values)

# Compute hyperbolic sine of the angles
hyperbolic_sine_values = np.sinh(angles_radians)
print("Hyperbolic Sine Values:", hyperbolic_sine_values)

# Compute hyperbolic cosine of the angles
hyperbolic_cosine_values = np.cosh(angles_radians)
print("Hyperbolic Cosine Values:", hyperbolic_cosine_values)

# Compute hyperbolic tangent of the angles
hyperbolic_tangent_values = np.tanh(angles_radians)
print("Hyperbolic Tangent Values:", hyperbolic_tangent_values)

# Compute inverse hyperbolic sine of the hyperbolic sine values
inverse_hyperbolic_sine_values = np.arcsinh(hyperbolic_sine_values)
print("Inverse Hyperbolic Sine Values:", inverse_hyperbolic_sine_values)

# Compute inverse hyperbolic cosine of the hyperbolic cosine values
inverse_hyperbolic_cosine_values = np.arccosh(hyperbolic_cosine_values)
print("Inverse Hyperbolic Cosine Values:", inverse_hyperbolic_cosine_values)

# Compute inverse hyperbolic tangent of the hyperbolic tangent values
inverse_hyperbolic_tangent_values = np.arctanh(hyperbolic_tangent_values)
print("Inverse Hyperbolic Tangent Values:", inverse_hyperbolic_tangent_values)

Angles in Radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine Values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine Values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent Values: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
Angles in Degrees Again: [ 0. 30. 45. 60. 90.]
Inverse Sine Values: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Inverse Cosine Values: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Inverse Tangent Values: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Hyperbolic Sine Values: [0.         0.54785347 0.86867096 1.24936705 2.3012989 ]
Hyperbolic Cosine Values: [1.         1.14023832 1.32460909 1.60028686 2.50917848]
Hyperbolic Tangent Values: [0.         0.48047278 0.6557942  0.78071444 0.91715234]
Inverse Hyperbolic Sine Values: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Inverse Hyperbolic Cosine Values: [0.       

## 12.14. Random Elements in `numpy`

**Random Number.** A random number signifies a number that cannot be logically predicted.

Do not confuse a random number with generating a different number every time we execute.

Since computers operate through algorithms, a program intended to generate random numbers implies that the numbers won't be truly random. Random numbers generated by an algorithm are known as **pseudo-random numbers**.

In this section, we will work with pseudo-random numbers and see how to generate them.

### 12.14.1.  `random` module

`numpy` has the `random` module dedicated to working with random numbers.

To generate random integers, we use the `.randint()` method.

In [67]:
from numpy import random

In [68]:
# Generate a random integer between 1 and 20
n = random.randint(1, 20)
print(n)

2


In [69]:
# Generate a random integer between 0 and 10
m = random.randint(10)
print(m)

2


To generate random real numbers within the interval [0, 1], we use the `.rand()` method.

In [70]:
# Generate a random real number between 0 and 1
x = random.rand()
print(x)

0.6369110291684156


### 12.14.2. Random arrays 

We can generate random arrays using both the `.randint()` method and the `.rand()` method.

In [71]:
# Generate a 1D array of 5 random integer elements
a = random.randint(100, size=5)
print(a)

[35 46  0 34 27]


In [72]:
# Generate a 1D array of 3 random real elements
b = random.rand(3)
print(b)

[0.15422037 0.58981999 0.58349173]


In [73]:
# Generate a 2D array of 5 arrays, each containing 4 random integers
c = random.randint(50, size=(5, 4))
print(c)

[[ 7  1  9  8]
 [39  9 32 45]
 [22 39 47 17]
 [19 18 49 35]
 [47 35 21 43]]


In [74]:
# Generate a 3D array of 2 arrays, each containing 4 arrays (2D), 
#   each of which contains 3 random real elements
d = random.rand(2, 4, 3)
print(d)

[[[0.15541026 0.0991186  0.10278302]
  [0.83830772 0.27744621 0.99637162]
  [0.81514038 0.28246065 0.89029944]
  [0.15615529 0.756627   0.36463012]]

 [[0.11294629 0.11077079 0.88815142]
  [0.4387201  0.66325038 0.11971715]
  [0.14392449 0.16316239 0.58555518]
  [0.80899526 0.73464631 0.06277218]]]


Given an array, we can randomly choose one of its elements using the `.choice()` method.

In [75]:
x = np.array([1, 2, 3, 4, 5, -5, -4, -3, -2, -1])
print(random.choice(x))

-1


The `.choice()` method also includes the `size` parameter, allowing us to generate a random array with elements from a given array:

In [76]:
print(random.choice(x, size = (3, 6)))

[[ 1 -5  1 -4  1 -2]
 [ 2 -3  4 -2 -5 -3]
 [-2  3 -4  2  3 -3]]


The `.choice()` method only takes one-dimensional arrays as parameters.

There is another parameter of the `.choice()` method that allows us to modify the probabilities of each element. This parameter is `p`, to which we must provide a list of probabilities (all elements must be less than or equal to 1, and the sum of all probabilities must be 1).

By default, all elements are equiprobable, meaning they have the same probability, which is $\frac{1}{n}$, where $n$ is the number of elements in the array.

In [77]:
x = np.array([1, 2, 3, 4, 5, -5, -4, -3, -2, -1])
print(random.choice(x, 
                    p = [0.2, 0.2, 0.05, 0.05, 0.05, 0.05, 0.1, 0.1, 0.05, 0.15],
                    size = (2, 6)))

[[-1 -1  1  2 -1  2]
 [ 4  1  1  2 -4  1]]


In the previous chunk, a 2D array with 2 1D arrays, each containing 6 elements, was generated. The probabilities for the elements of the original array are as follows:

- Elements `1` and `2` have a probability of 0.2 of occurring.
- Element `-1` has a probability of 0.15.
- Elements `-4` and `-3` have a probability of 0.1 of occurring.
- Elements `3`, `4`, `5`, `6`, and `-2` have a probability of 0.05.

All probabilities are in the range [0, 1], and their sum is 1.

**Permutation.** A permutation of an array refers to the rearrangement of its elements.

The `random` module of `numpy` provides two methods for creating random permutations of a given array:

* `.shuffle()` modifies the original array.
* `.permutation()` creates a copy.

In [78]:
a = np.array([1, 2, 3, 4])
random.shuffle(a)

print("Shuffled Original Array:", a)

Shuffled Original Array: [3 2 4 1]


In [79]:
a = np.array([1, 2, 3, 4])
b = random.permutation(a)

print("Permuted Original Array:", b)
print("Original Array:", a)

Permuted Original Array: [4 2 1 3]
Original Array: [1 2 3 4]


## 12.15. Universal Functions

Universal functions are those that operate on the ndarray object.

We can check if a method is a universal function using the `type` function. When it is a universal function, we obtain that its type is `np.ufunc`.

In [80]:
# It is a universal function
print(type(np.multiply))

<class 'numpy.ufunc'>


In [81]:
type(np.multiply) == np.ufunc

True

In [82]:
# It is not a universal function
print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


In [83]:
type(np.concatenate) == np.ufunc

False

### 12.15.1. Creating Our Own Universal Functions

To create our own universal function, we first need to define a function as we learned. Then, we add it to `numpy` using the `.frompyfunc()` method, which takes the function `function`, the number of inputs (arrays), `inputs`, and the number of arrays it returns, `outputs`:

In [84]:
def my_sum(x, y):
  return x + y

my_sum = np.frompyfunc(my_sum, 2, 1) 
# function = my_sum
# inputs = 2, as my_sum takes two arrays
# outputs = 1, as my_sum returns one array, the sum array

a = np.array([1, 0, 7])
b = np.array([-1, 2, 5])
print(my_sum(a, b))

[0 2 12]


In [85]:
my_sum(np.array([[1,2], [3,4]]), np.array([[1,0], [-1,0]]))

array([[2, 2],
       [2, 4]], dtype=object)

In [86]:
print(type(my_sum))

<class 'numpy.ufunc'>


## 12.16. Problems

### 12.16.1. Problem 1

- Create the following matrices:
\begin{equation}
x =
\begin{pmatrix}
1 & 4 & 3 
\end{pmatrix}
\end{equation}

\begin{equation}
y =
\begin{pmatrix}
1 & 4 & 3 \\
9 & 2 & 7 
\end{pmatrix}
\end{equation}

Find the rows, columns, and total size of the matrix `y`. Obtain the element in the first row and the second column of the matrix `y`. Get the first row of the matrix `y`. Get the last column of the matrix `y`. Get the first and third column of the matrix `y`.

In [87]:
import numpy as np

In [88]:
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [89]:
y = np.array([[1, 4, 3], [9, 2, 7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [90]:
y.shape

(2, 3)

In [91]:
y.size

6

In [92]:
y[0,1]

4

In [93]:
y[0, :]

array([1, 4, 3])

In [94]:
y[:, -1]

array([3, 7])

In [95]:
y[:, [0, 2]]

array([[1, 3],
       [9, 7]])

### 12.16.2. Problem 2

Create an array `z` from 1 to 2000 with a step of 1. Generate an array with `[0.5, 1, 1.5, 2, 2.5]`. Use `linspace` to generate an array starting from 3, ending at 9, and containing 10 elements.

In [96]:
z = np.arange(1, 2000, 1)
z

array([   1,    2,    3, ..., 1997, 1998, 1999])

In [97]:
np.arange(0.5, 3, 0.5)

array([0.5, 1. , 1.5, 2. , 2.5])

In [98]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

### 12.16.3. Problem 3

Generate a 3 $\times$ 5 array with all elements as 0. Generate a 5 $\times$ 3 array with all elements as 1. Generate an empty 1D array with 3 elements.

In [99]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [100]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [101]:
np.empty(3)

array([4.24399158e-314, 4.23762559e-311, 4.24186959e-311])

### 12.16.4. Problem 4

Let `a = [1, 2, 3, 4, 5, 6]`. Reassign the fourth element of `a` to 7. Reassign the first, second, and third elements to 1. Reassign the second, third, and fourth elements to 9, 8, and 7.

In [102]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [103]:
a[3] = 7
a

array([1, 2, 3, 7, 5, 6])

In [104]:
a[:3] = 1
a

array([1, 1, 1, 7, 5, 6])

In [105]:
a[1:4] = [9, 8, 7]
a

array([1, 9, 8, 7, 5, 6])

### 12.16.5. Problem 5

Create a 2 $\times$ 2 array of zeros `b` and set $b = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ using matrix indexing.

In [106]:
b = np.zeros((2, 2))
b[0, 0] = 1
b[0, 1] = 2
b[1, 0] = 3
b[1, 1] = 4

b

array([[1., 2.],
       [3., 4.]])

### 12.16.6. Problem 6

Let $b = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$. Multiply and divide `b` by 2. Square each element of `b`. Let `c` be a scalar. Verify the reflexivity of scalar addition and multiplication: `b + c = c + b` and `cb = bc`.

In [107]:
b + 2

array([[3., 4.],
       [5., 6.]])

In [108]:
b - 2

array([[-1.,  0.],
       [ 1.,  2.]])

In [109]:
2 * b

array([[2., 4.],
       [6., 8.]])

In [110]:
b / 2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [111]:
b**2

array([[ 1.,  4.],
       [ 9., 16.]])

### 12.16.7. Problem 7

Let $b = \begin{pmatrix} 1 & 2 \\ 3 & 4 \end{pmatrix}$ and $d = \begin{pmatrix} 3 & 4 \\ 5 & 6 \end{pmatrix}$. Compute `b + d` and `b - d`. Calculate `b * d`, `b / d`, and `b**d`. Calculate the transpose of matrix `b`.

In [112]:
b = np.array([[1, 2], [3, 4]])
d = np.array([[3, 4], [5, 6]])

In [113]:
b + d

array([[ 4,  6],
       [ 8, 10]])

In [114]:
b - d

array([[-2, -2],
       [-2, -2]])

In [115]:
b * d

array([[ 3,  8],
       [15, 24]])

In [116]:
b / d

array([[0.33333333, 0.5       ],
       [0.6       , 0.66666667]])

In [117]:
b**d

array([[   1,   16],
       [ 243, 4096]])

In [118]:
b.T

array([[1, 3],
       [2, 4]])

### 12.16.8. Problem 8

Calculate `np.sqrt` for `x = [1, 4, 9, 16]`.

In [119]:
x = [1, 4, 9, 16]
np.sqrt(x)

array([1., 2., 3., 4.])

### 12.16.9. Problem 9

Check which elements of the array `x = [1, 2, 4, 5, 9, 3]` are greater than 3 and which elements in `x` are larger than the corresponding element in `y = [0, 2, 3, 1, 2, 3]`.

In [120]:
x = np.array([1, 2, 4, 5, 9, 3])
y = np.array([0, 2, 3, 1, 2, 3])

In [121]:
x > 3

array([False, False,  True,  True,  True, False])

In [122]:
x > y

array([ True, False,  True,  True,  True, False])

### 12.16.10. Problem 10

Let `x` be the same matrix as in the previous problem. Create a variable `y` containing all elements of `x` that are strictly greater than 3. Assign the value 0 to all values of `x` that are greater than 3.

In [123]:
y = x[x > 3]
y

array([4, 5, 9])

In [124]:
x[x > 3] = 0
x

array([1, 2, 0, 0, 0, 3])